# Generated by Django 5.2.4 on 2025-07-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
    ]
